apiVersion: v1
kind: ServiceAccount
metadata:
  name: morgan-sqs-role
  namespace: notification-service-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452968854315:role/morgan-sqs-role

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452968854315:role/morgan-amazoneks_loadbalancer_controller_role