apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-app-service-account
  namespace: notification-service-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452968854315:role/morgan-sqs_role