apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-q3
  namespace: notification-service-app
  labels:
    app: notification-service-q3
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: morgan
  template:
    metadata:
      labels:
        app: morgan
    spec:
      serviceAccountName: morgan-sqs-role
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: notification-service-q3
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: notification-service-q3
      containers:
        - name: notification-service-q3
          image: public.ecr.aws/i3m8z0o9/morgan/queues-repo:AWSProject_P3Service
          imagePullPolicy: Always
          ports:
          - containerPort: 5003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: notification-service-config
                key: AWS_REGION
          - name: AWS_Q3
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q3
                key: AWS_Q3
          - name: SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q3
                key: SENDER_EMAIL
          - name: RECIPIENT_EMAIL
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q3
                key: RECIPIENT_EMAIL