apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-q2
  namespace: notification-service-app
  labels:
    app: notification-service-q2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: morgan
  template:
    metadata:
      labels:
        app: morgan
    spec:
      serviceAccountName: morgan-sqs-role
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: notification-service-q2
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: notification-service-q2
      containers:
        - name: notification-service-q2
          image: public.ecr.aws/i3m8z0o9/morgan/queues-repo:AWSProject_P2Service
          imagePullPolicy: Always
          ports:
          - containerPort: 5002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: notification-service-config
                key: AWS_REGION
          - name: AWS_Q2
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q2
                key: AWS_Q2
          - name: JIRA_KEY
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q2
                key: JIRA_KEY
          - name: EMAIL
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q2
                key: EMAIL
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q2
                key: HOST
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: notification-service-secrets-q2
                key: PROJECT_ID                              